apiVersion: v1
kind: Service
metadata:
  name: gmvis-web
  labels:
    {{- include "gmvis.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "gmvis.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.web.port }}
      targetPort: http
