apiVersion: v1
kind: Service
metadata:
  name: gmvis-api
  labels:
    app.kubernetes.io/name: gmvis-api
    app.kubernetes.io/part-of: gmvis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gmvis-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
