---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
  name: gmvis-app
  namespace: prod-gmvis
spec:
  encryptedData:
    ADMIN_PASSWORD: AgBiSJNyIMHmqCHay6LwvrivC1wQuSQpo1ekWh/MYEkXo8OqoFDj0cYkDStCEEy79TuqzdzE8IzQKl5R3dT9O1b9/idGgopiGm0adSLwT/uj77eb0R8cjejFwHbusDQBt8iU22yOR1foLU3vRai0lFvrLsiiINJ2ZxYm6CPbjEKK6TZr6wEgYDKO/4IybucD4uB4OeUtTpkU1J08l06zabtQapyhGdIKfMMqj14w1CyGVFI1thExhVNhFylHcMzlchFU5AuJK+7qePHqyagOKuNSZAUDiD40pKHQUyISeRLCHMYJMLLXR7j6ZhagQRSx1h+bBIO3hgoY4Zw4A1ehlWyNv7Yc0q/cw+duDPzaTg7EuDWpBjDzVH4M2hSSS2z0ttGwL4EgQUU7VlsXn38GDkWJ0rduMh9BjleafVHxobjnAoTNjgTRiaa6Bnj/5y8d2ezGsuvwwAHMui6PsDiKT4otJNmihO8L2dL4uqHBKROEUjrFE9GIGWvch0V+9XZxbuzCTM0BDhbpOL7p8iNx7/7iExokqXnjM2JuCPTgOrx3nKtsvU6aXNsbQ/L29YOXI4AXyrF507sYrcbrRSosrUYt9BJLy9lPd+yv6CqRaVU/fovUSu2hLxiU0YMCmhNVQDqzz3EDY4MFMPa80N57ZP6E6CnXxD6WBRv9pXtrkc8Iyo/ozmYiwi79SIGn4pLv9gsbeJ6Aq3C9DaHTpiDmStIa16IWHeGKzticWlIAhRIe4FcvmIOD9uk57qlVVy8FQ1bkr9pLYKH+NMvjisa+lwde
    SESSION_SECRET: AgAxMg+MA4z0PxuF7akaRwwTyZub1pI3Nd+E2uuclnF0rFGbt9499AxdWkPharvHl+IRY98E4748YTBJR62JYJ+WEJy5Oocb7EzGLgUusFwzCSGBFWE74LjT8S+/E8JLPjk3vHdmCd2hu0Gjo/fR+PoVUsw4pOsmAaocOzaSi3YOXiqE31TagcrfhqOd/qGrVjDo6cKUriIULG9bcpN4MRwBYhhp6CJlJFHgohSlqmAo/QY1fXWPec8L2ET4ciOedPVXfspjn84hb9xhLVyHQb9LD7jSwYk5pHkBqkrVYgprzfeVxI+cmjepEWO1F52Azrnuk5lBKC4fGt5viCgK00GV1mXbliAphq32+fs/dhERoFmrMj2IvHb2ArbZgQbNhWpazOHiM0LctzXA4LH2OR3ADUO/IndVCbbMpzB0ilycmW0AycIVZWJzAZxeWulpU9GFR7tH2BI8eO+3XnFNjGPFeUlq/j9xaIvnywr+EL2FUfamhRBiomQVy1HjMus5kYp9kCL5ebrdLfsqu3nr8GXctV/SEuB2rQy+FZYeXBoOCD2ZCBJTIM8DndfBpeU2MPLwt3GaGezmewdM4KoO48+qlpfOuQicnskZ3LnZobpKbFDaTWAgUiNGd4sMwydck3ui7cBDL62UzHILdn9AtfzyLkLubDy2UY4kdUKQLEnNisZ+acaKQzqsD0waQIgc7d1zyDaShwZRE092GCkzE1SIj28GQawo/8cLkmb+AtwSsA5dW3+R/QPCxqS/70QuguDq1X5qMJxxw8RmHUxHVbX6
  template:
    metadata:
      name: gmvis-app
      namespace: prod-gmvis
    type: Opaque
