---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
  name: ghcr-pull
  namespace: prod-gmvis
spec:
  encryptedData:
    .dockerconfigjson: AgAJ4G1ilW++ePgZKh3AwVT/XLnPW0grMx3LqX0EDIeJq9iSL5gLoSZa/iBT6+Zkaqz9R5Pql5QWgABjHVGuGCzv7o1S/6sX1m5fQSY/pnBcDinQUlNDt1ohtEUVtC0h9k7moJ3lPbkmMVRBs9QVoupp86i+b4s2OCJTz9W44v5GCe1EaxWgv7LXt0xhmlJ6RHuxdSjhUdvnASdEAJaV1kP4rrVfgkklhhzQdv3e8Rh+b2DElwHV0qk3mQN/1w+ckq5USbssNfoPwDtSowsXyW+Ls77NprI/X7c0f1zcLnmzkdngWklEaUTmAiUFvk9v5HzVKLElle2xjMcm2iAXeUPE71IGgE6xbesUXvd7WiqH02N7+fTCgGcP6b4DXbUJ9AmeS/L0DSWrVfaavyhRzPZ8X8g2BFy2HDNS2XtPwZQ14zR4PD3R/4b1SVA3Y01XY5vHbmhZAUNyB4uD0d2cGw6rxygzv5jxMnCwTvFAZjaB6273ET+1EGrVRq7lJErA9G6jn8WcI0ooSL64qwfiLwsPeOixRzX/JH7s4e/L7T2BXANqcS/WR2hx+GVGIv0TSk9XrlvvBq0QoAObdn4PtEveRRfK5sDEMjDCl85xKiD/tX8sveF/fAXZnilPPJriih1pN/E032CjhGrOsmssZChQ59rMzx4S3UnHKs7P4qsrUaFeKkc123IJUhOMhaxhw8B5u5ThirgVA6f2NIaS7xRWzz6MESux3FxvAkiMThbOhizk6Cf/cNA05Ge6XjV8B9YkTGNWbx7pEwJwoQfT1pbJhUq4Z3eouCN1b4b2DsinaBxPOhtSa+KX92Xp01YxtkmE
  template:
    metadata:
      name: ghcr-pull
      namespace: prod-gmvis
    type: kubernetes.io/dockerconfigjson
